name: v3 Sync Tenant Repo to Main Repo 

on:
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: 4472-M/github-action-demo
          ref: refs/heads/main


      - name: deployment 
        run: |
          scp index.html test@13.201.12.23:/var/www/html
